name: Sync "sub-*" into "main-revision-skipperwraith"

on:
  push:
    branches: 
      'sub-**'


permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write

jobs:
  update-sync:
    name: Merge "sub-*" into "main-revision-skipperwraith"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
      - name: Merge Master to Production branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_branch: $GITHUB_HEAD_REF
          to_branch: main-revision-skipperwraith
